language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: VDo/qrZ+mh1YWElnNo3h0SMY6phUuclwEIQ5SMq9oWIRVqD+VQsfV8d8AeODVrfXKXgTjHJHwSYTU+vhfYARruEQzyUnz+kUPVrWRZoJrOsqVJcdASd5x/kBVGZ3MPCfyqc5DDj0lsJ6jf+mADWcEa04Ap3gmGyP87/OfLc2uE1qpKNPp9s/PmP6nNpvCdyqzbJZ4BpMVyiPBtD9aKeKus64L8B2HOU4bdmN42Egb49/5Ye428Wfqdq6T+3B9l7r5q2k+jyr9qK7LTAqur5nBNTj23pMq4sfO4ERsBLfIBe2eN4oCBSQisOacIUBsydpQDebUr9TrUlXDJ3pDC+WJsJ8lcXfPNU2plNkJ96CAWx2IM7Mg59VGq5JG54BMNSUDqYNI3bsLYKfZzznpXQPe5Kfb4kd8Os41FQmfjUidyQ3jUt8FYQqRrPvv1s7U8aofhBan9aw3ONYDmk2LJPApNKYtPBauzDMtzJ2KIJebOQP+7c7lc6ZjgbUjnfgbK+45tTJAhxPb7RkzaiXUB3a52efsk/qPfwrWw0LfTBHwI3bbwnmJY8wY6NnjmSfhb1KpUOnumZ1MS63H67DT0lUhsWcrB2OzsA7ttozawJp0IL/WcvT6vVo44bGs6INFMPCOy14dd/YMYPibjICbGjliiSxcf0yoOq12ZHSLwnHSxs=
  app: restaurant-guide-challenge
